name: samurai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - onnxruntime>=1.20.0
    - opencv-python>=4.8.0
    - numpy>=1.24.0
    - matplotlib>=3.7.0
    - pandas>=2.0.0
    - scipy>=1.10.0
    - loguru>=0.7.0
    - tikzplotlib
    - jpeg4py
    - lmdb
